package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Tembocs/fuse5/compiler/mir"
)

// EmitC11 returns a freestanding ISO C11 translation unit for the
// given MIR Module. The output is deterministic — byte-identical
// across runs and platforms for the same input (Rule 7.1).
//
// Errors indicate a MIR instruction outside the W05 subset; they are
// compiler bugs, not user errors, because the lowerer should have
// caught any user-reachable form before MIR reached the emitter.
func EmitC11(m *mir.Module) (string, error) {
	// Emit functions in sorted name order for determinism.
	names := m.SortedFunctionNames()
	byName := map[string]*mir.Function{}
	for _, f := range m.Functions {
		byName[f.Name] = f
	}

	var sb strings.Builder
	sb.WriteString("/* Generated by fuse. Do not edit. */\n")
	sb.WriteString("#include <stdint.h>\n\n")

	mainFn, hasMain := byName["main"]
	// Forward-declare every non-main function so calls inside any
	// body resolve regardless of definition order.
	for _, name := range names {
		if name == "main" {
			continue
		}
		if err := emitFunctionProto(&sb, byName[name]); err != nil {
			return "", err
		}
	}
	sb.WriteByte('\n')
	// Emit every non-main function as an int64_t-returning C function.
	// Main gets special treatment so the C entry point is a standard
	// `int main(void)`.
	for _, name := range names {
		if name == "main" {
			continue
		}
		if err := emitFunction(&sb, byName[name], false); err != nil {
			return "", err
		}
		sb.WriteByte('\n')
	}

	if hasMain {
		if err := emitFunction(&sb, mainFn, true); err != nil {
			return "", err
		}
	}
	return sb.String(), nil
}

// emitFunctionProto writes a forward declaration for f so its
// callers resolve even when the definition comes later in the
// translation unit. Only used for non-main functions.
func emitFunctionProto(sb *strings.Builder, f *mir.Function) error {
	fmt.Fprintf(sb, "int64_t %s(", cName(f.Module, f.Name))
	if f.NumParams == 0 {
		sb.WriteString("void")
	} else {
		for i := 0; i < f.NumParams; i++ {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "int64_t p%d", i)
		}
	}
	sb.WriteString(");\n")
	return nil
}

// emitFunction writes one MIR Function. When asMain is true the
// function is emitted as `int main(void)` and the return register is
// narrowed to `int` with an explicit cast.
func emitFunction(sb *strings.Builder, f *mir.Function, asMain bool) error {
	if asMain {
		if f.NumParams != 0 {
			return fmt.Errorf("fn main must be zero-arg at this wave, got %d params", f.NumParams)
		}
		sb.WriteString("int main(void) {\n")
	} else if f.NumParams == 0 {
		fmt.Fprintf(sb, "int64_t %s(void) {\n", cName(f.Module, f.Name))
	} else {
		fmt.Fprintf(sb, "int64_t %s(", cName(f.Module, f.Name))
		for i := 0; i < f.NumParams; i++ {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "int64_t p%d", i)
		}
		sb.WriteString(") {\n")
	}
	// Emit each block in allocation order with a stable label so
	// branches (W06+) can target them. At W05 there's no branching,
	// so we just emit sequentially without labels.
	// Pre-compute the register set so we can declare all locals at
	// the top of the function body — required for ISO C11 mixed-
	// declaration portability.
	var regs []mir.Reg
	for _, blk := range f.Blocks {
		for _, in := range blk.Insts {
			if in.Dst != mir.NoReg {
				regs = append(regs, in.Dst)
			}
		}
	}
	sort.Slice(regs, func(i, j int) bool { return regs[i] < regs[j] })
	for _, r := range regs {
		fmt.Fprintf(sb, "    int64_t r%d;\n", r)
	}
	if len(regs) > 0 {
		sb.WriteByte('\n')
	}
	for _, blk := range f.Blocks {
		for _, in := range blk.Insts {
			if err := emitInst(sb, in); err != nil {
				return fmt.Errorf("fn %s block %d: %w", f.Name, blk.ID, err)
			}
		}
		switch blk.Term {
		case mir.TermReturn:
			if asMain {
				// Narrow to int; preserves low 32 bits.
				fmt.Fprintf(sb, "    return (int)r%d;\n", blk.ReturnReg)
			} else {
				fmt.Fprintf(sb, "    return r%d;\n", blk.ReturnReg)
			}
		default:
			return fmt.Errorf("fn %s block %d: unsupported terminator %s (W05 allows return only)",
				f.Name, blk.ID, blk.Term)
		}
	}
	sb.WriteString("}\n")
	return nil
}

// emitInst writes one MIR instruction in C11 form. The instruction
// set is exactly the W05 subset; anything else is a bridge bug.
func emitInst(sb *strings.Builder, in mir.Inst) error {
	switch in.Op {
	case mir.OpConstInt:
		fmt.Fprintf(sb, "    r%d = INT64_C(%d);\n", in.Dst, in.IntValue)
	case mir.OpAdd:
		fmt.Fprintf(sb, "    r%d = r%d + r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpSub:
		fmt.Fprintf(sb, "    r%d = r%d - r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpMul:
		fmt.Fprintf(sb, "    r%d = r%d * r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpDiv:
		fmt.Fprintf(sb, "    r%d = r%d / r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpMod:
		fmt.Fprintf(sb, "    r%d = r%d %% r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpParam:
		fmt.Fprintf(sb, "    r%d = p%d;\n", in.Dst, in.ParamIndex)
	case mir.OpCall:
		fmt.Fprintf(sb, "    r%d = %s(", in.Dst, in.CallName)
		for i, a := range in.CallArgs {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "r%d", a)
		}
		sb.WriteString(");\n")
	default:
		return fmt.Errorf("unsupported MIR op %s (W06 subset: const_int/add/sub/mul/div/mod/param/call)", in.Op)
	}
	return nil
}

// cName produces a C-safe identifier for a MIR function that is not
// `main`. The scheme folds the module path into the name so that
// multi-module programs at later waves don't collide; at W05 the
// main module is empty so non-main names degenerate to the bare
// function name prefixed with `fuse_`.
func cName(module, name string) string {
	safe := func(s string) string {
		b := make([]byte, 0, len(s))
		for i := 0; i < len(s); i++ {
			c := s[i]
			if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
				b = append(b, c)
			} else {
				b = append(b, '_')
			}
		}
		return string(b)
	}
	if module == "" {
		return "fuse_" + safe(name)
	}
	return "fuse_" + safe(module) + "__" + safe(name)
}
