package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Tembocs/fuse5/compiler/mir"
)

// EmitOptions tunes codegen emission. Zero value is "no debug info,
// no source attribution" — the historical EmitC11 behavior. W24 added
// per-statement `#line` directive support gated by Debug + SourceFile.
type EmitOptions struct {
	// Debug, when true, causes emitInst to emit a `#line N "source"`
	// directive whenever the MIR instruction's Line field changes.
	// This gives gdb / lldb per-statement mappings back to Fuse
	// source, which is what the W24 stub "compiler-emitted debug-
	// line directives per MIR statement" retires.
	Debug bool
	// SourceFile is the `.fuse` source filename placed in every
	// `#line` directive. When empty, the emitter falls back to
	// `<fuse>`. Path separators are normalised by EmitLineDirective
	// so goldens stay stable across hosts.
	SourceFile string
}

// EmitC11 is the historical signature retained for callers that do
// not need debug-line directives. Delegates to EmitC11WithOptions
// with a zero Options value (Debug=false, SourceFile=""), which
// preserves the pre-W24 byte-stable output.
func EmitC11(m *mir.Module) (string, error) {
	return EmitC11WithOptions(m, EmitOptions{})
}

// EmitC11WithOptions is the W24+ entry point. Behavior is
// identical to EmitC11 when opts.Debug is false; when Debug is
// true, the emitter inserts `#line N "source"` directives ahead
// of every MIR instruction whose Line differs from the preceding
// one. The output is still deterministic (Rule 7.1) — line numbers
// are pinned by the lowerer at lower time, so identical input
// still produces identical output.
//
// Errors indicate a MIR instruction outside the supported subset;
// they are compiler bugs, not user errors, because the lowerer
// should have caught any user-reachable form before MIR reached
// the emitter.
func EmitC11WithOptions(m *mir.Module, opts EmitOptions) (string, error) {
	// Emit functions in sorted name order for determinism.
	names := m.SortedFunctionNames()
	byName := map[string]*mir.Function{}
	for _, f := range m.Functions {
		byName[f.Name] = f
	}

	var sb strings.Builder
	sb.WriteString("/* Generated by fuse. Do not edit. */\n")
	sb.WriteString("#include <stdint.h>\n")
	// W17: float↔int casts use memcpy; struct_new uses fuse_rt_alloc.
	// Pull the needed headers in when the module needs them.
	needsRuntime := usesRuntimeABI(m) || usesStructAlloc(m)
	needsMemcpy := usesFloatBitCasts(m)
	if needsMemcpy {
		sb.WriteString("#include <string.h>\n")
	}
	if needsRuntime {
		sb.WriteString("#include \"fuse_rt.h\"\n")
	}
	sb.WriteByte('\n')

	mainFn, hasMain := byName["main"]
	// Forward-declare every non-main function so calls inside any
	// body resolve regardless of definition order.
	for _, name := range names {
		if name == "main" {
			continue
		}
		if err := emitFunctionProto(&sb, byName[name]); err != nil {
			return "", err
		}
	}
	sb.WriteByte('\n')
	// Emit every non-main function as an int64_t-returning C function.
	// Main gets special treatment so the C entry point is a standard
	// `int main(void)`.
	for _, name := range names {
		if name == "main" {
			continue
		}
		if err := emitFunction(&sb, byName[name], false, opts); err != nil {
			return "", err
		}
		sb.WriteByte('\n')
	}

	if hasMain {
		if err := emitFunction(&sb, mainFn, true, opts); err != nil {
			return "", err
		}
	}
	return sb.String(), nil
}

// emitFunctionProto writes a forward declaration for f so its
// callers resolve even when the definition comes later in the
// translation unit. Only used for non-main functions.
func emitFunctionProto(sb *strings.Builder, f *mir.Function) error {
	fmt.Fprintf(sb, "int64_t %s(", cName(f.Module, f.Name))
	if f.NumParams == 0 {
		sb.WriteString("void")
	} else {
		for i := 0; i < f.NumParams; i++ {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "int64_t p%d", i)
		}
	}
	sb.WriteString(");\n")
	return nil
}

// emitFunction writes one MIR Function. When asMain is true the
// function is emitted as `int main(void)` and the return register is
// narrowed to `int` with an explicit cast. opts.Debug toggles the
// emission of per-statement `#line` directives.
func emitFunction(sb *strings.Builder, f *mir.Function, asMain bool, opts EmitOptions) error {
	if asMain {
		if f.NumParams != 0 {
			return fmt.Errorf("fn main must be zero-arg at this wave, got %d params", f.NumParams)
		}
		sb.WriteString("int main(void) {\n")
	} else if f.NumParams == 0 {
		fmt.Fprintf(sb, "int64_t %s(void) {\n", cName(f.Module, f.Name))
	} else {
		fmt.Fprintf(sb, "int64_t %s(", cName(f.Module, f.Name))
		for i := 0; i < f.NumParams; i++ {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "int64_t p%d", i)
		}
		sb.WriteString(") {\n")
	}
	// Emit each block in allocation order with a stable label so
	// branches (W06+) can target them. At W05 there's no branching,
	// so we just emit sequentially without labels.
	// Pre-compute the register set so we can declare all locals at
	// the top of the function body — required for ISO C11 mixed-
	// declaration portability.
	// Dedupe destination registers: match-arm lowering reassigns
	// the same shared result register from multiple blocks, and
	// declaring it twice would be a C redeclaration error.
	regSet := map[mir.Reg]bool{}
	for _, blk := range f.Blocks {
		for _, in := range blk.Insts {
			if in.Dst != mir.NoReg {
				regSet[in.Dst] = true
			}
		}
	}
	regs := make([]mir.Reg, 0, len(regSet))
	for r := range regSet {
		regs = append(regs, r)
	}
	sort.Slice(regs, func(i, j int) bool { return regs[i] < regs[j] })
	for _, r := range regs {
		fmt.Fprintf(sb, "    int64_t r%d;\n", r)
	}
	if len(regs) > 0 {
		sb.WriteByte('\n')
	}
	// When the function has more than one block, emit labels so
	// branches (TermJump / TermIfEq) can target them. The label
	// scheme is `L<blockID>:` — simple, deterministic, C-safe.
	needLabels := len(f.Blocks) > 1
	// lastLine tracks the most recent source line a `#line` directive
	// pointed at. Emitted directives are stateful at the C
	// preprocessor level — once `#line N` fires, every subsequent C
	// line is understood to be that Fuse line until another directive
	// changes it. The comparison skips zero-line insts (synthetic
	// ops the lowerer produced without a source position).
	lastLine := 0
	for _, blk := range f.Blocks {
		if needLabels {
			fmt.Fprintf(sb, "L%d:\n", blk.ID)
		}
		for _, in := range blk.Insts {
			if opts.Debug && in.Line > 0 && in.Line != lastLine {
				fmt.Fprintf(sb, "%s\n", EmitLineDirective(in.Line, opts.SourceFile))
				lastLine = in.Line
			}
			if err := emitInst(sb, in); err != nil {
				return fmt.Errorf("fn %s block %d: %w", f.Name, blk.ID, err)
			}
		}
		switch blk.Term {
		case mir.TermReturn:
			if asMain {
				// Narrow to int; preserves low 32 bits.
				fmt.Fprintf(sb, "    return (int)r%d;\n", blk.ReturnReg)
			} else {
				fmt.Fprintf(sb, "    return r%d;\n", blk.ReturnReg)
			}
		case mir.TermJump:
			fmt.Fprintf(sb, "    goto L%d;\n", blk.JumpTarget)
		case mir.TermIfEq:
			fmt.Fprintf(sb, "    if (r%d == (int64_t)%d) goto L%d; else goto L%d;\n",
				blk.BranchReg, blk.BranchConst, blk.TrueTarget, blk.FalseTarget)
		case mir.TermUnreachable:
			// Reference §57.4: a divergent block has no successors.
			// Emit two lines: (1) the EmitIntrinsic("unreachable")
			// optimizer hint (__builtin_unreachable()) so the
			// backend can prune downstream code and tighten
			// register allocation, (2) the fuse_rt_abort belt-and-
			// braces guard so the program still traps loudly if a
			// release build folds the intrinsic into a no-op path.
			sb.WriteString("    /* unreachable */\n")
			fmt.Fprintf(sb, "    %s;\n", EmitIntrinsic("unreachable", nil))
			sb.WriteString("    fuse_rt_abort(\"unreachable\");\n")
		default:
			return fmt.Errorf("fn %s block %d: unsupported terminator %s",
				f.Name, blk.ID, blk.Term)
		}
	}
	sb.WriteString("}\n")
	return nil
}

// emitInst writes one MIR instruction in C11 form. The instruction
// set is exactly the W05 subset; anything else is a bridge bug.
func emitInst(sb *strings.Builder, in mir.Inst) error {
	switch in.Op {
	case mir.OpConstInt:
		fmt.Fprintf(sb, "    r%d = INT64_C(%d);\n", in.Dst, in.IntValue)
	case mir.OpAdd:
		fmt.Fprintf(sb, "    r%d = r%d + r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpSub:
		fmt.Fprintf(sb, "    r%d = r%d - r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpMul:
		fmt.Fprintf(sb, "    r%d = r%d * r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpDiv:
		fmt.Fprintf(sb, "    r%d = r%d / r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpMod:
		fmt.Fprintf(sb, "    r%d = r%d %% r%d;\n", in.Dst, in.Lhs, in.Rhs)
	case mir.OpParam:
		fmt.Fprintf(sb, "    r%d = p%d;\n", in.Dst, in.ParamIndex)
	case mir.OpCall:
		// Compiler-intrinsic call names are prefixed with
		// "__fuse_intrinsic_" (stable ABI for the lowerer → codegen
		// hand-off) and routed to the EmitIntrinsic / EmitPtrNull /
		// EmitSizeOf helpers rather than emitted as a plain C call.
		// A normal function call falls through to the default
		// `name(args...)` path. This keeps the intrinsic dispatch
		// wired even before the source-level plumbing that creates
		// these calls lands — any lowerer that emits a
		// `__fuse_intrinsic_*` OpCall gets the right expansion
		// today.
		if expansion, ok := tryEmitCompilerIntrinsic(in); ok {
			fmt.Fprintf(sb, "    r%d = %s;\n", in.Dst, expansion)
			return nil
		}
		fmt.Fprintf(sb, "    r%d = %s(", in.Dst, in.CallName)
		for i, a := range in.CallArgs {
			if i > 0 {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "r%d", a)
		}
		sb.WriteString(");\n")
	case mir.OpDrop:
		// Destructor call: `TypeName_drop(&rN);`. When Lhs is
		// NoReg the drop is a best-effort hint that codegen
		// emits as a call with no address argument — useful for
		// static destructors that manage their own state.
		if in.Lhs == mir.NoReg {
			fmt.Fprintf(sb, "    %s();\n", in.CallName)
		} else {
			fmt.Fprintf(sb, "    %s(&r%d);\n", in.CallName, in.Lhs)
		}
	case mir.OpSpawn:
		// fuse_rt_thread_spawn((int64_t(*)(void*))entry, arg_as_ptr);
		// The entry-fn cast matches the runtime trampoline's
		// int64_t(*)(void*) expected signature. W17 codegen
		// hardening will emit a proper thunk; the current cast is
		// ABI-correct for integer-register parameters on x86_64 /
		// MSVC-x64 but not for floating-point entries.
		fmt.Fprintf(sb, "    r%d = (int64_t)(intptr_t)fuse_rt_thread_spawn((int64_t(*)(void*))&%s, ", in.Dst, in.CallName)
		if len(in.CallArgs) == 0 {
			sb.WriteString("(void*)0")
		} else {
			fmt.Fprintf(sb, "(void*)(intptr_t)r%d", in.CallArgs[0])
		}
		sb.WriteString(");\n")
	case mir.OpThreadJoin:
		fmt.Fprintf(sb, "    r%d = fuse_rt_thread_join((void*)(intptr_t)r%d);\n", in.Dst, in.Lhs)
	case mir.OpChanNew:
		fmt.Fprintf(sb, "    r%d = (int64_t)(intptr_t)fuse_rt_chan_new(r%d, r%d);\n",
			in.Dst, in.Lhs, in.Rhs)
	case mir.OpChanSend:
		fmt.Fprintf(sb, "    r%d = (int64_t)fuse_rt_chan_send((void*)(intptr_t)r%d, (const void*)&r%d);\n",
			in.Dst, in.Lhs, in.Rhs)
	case mir.OpChanRecv:
		fmt.Fprintf(sb, "    r%d = (int64_t)fuse_rt_chan_recv((void*)(intptr_t)r%d, (void*)&r%d);\n",
			in.Dst, in.Lhs, in.Rhs)
	case mir.OpChanClose:
		fmt.Fprintf(sb, "    fuse_rt_chan_close((void*)(intptr_t)r%d);\n", in.Lhs)
	case mir.OpPanic:
		fmt.Fprintf(sb, "    fuse_rt_panic(%s);\n", cEscapeString(in.CallName))
	default:
		// W15 consolidation ops: route through emitW15Inst.
		if ok, err := emitW15Inst(sb, in); ok {
			return err
		}
		return fmt.Errorf("unsupported MIR op %s (W09 subset plus W15/W16 consolidation ops)", in.Op)
	}
	return nil
}

// UsesRuntimeABI is the exported form of usesRuntimeABI so the
// driver can decide whether to link libfuse_rt.a and pass the
// runtime include directory to the C compiler. The emitter calls
// the unexported path internally; callers outside codegen use
// this name to stay at the package-API boundary.
func UsesRuntimeABI(m *mir.Module) bool { return usesRuntimeABI(m) }

// usesStructAlloc returns true when the module contains an
// OpStructNew — the op emits a fuse_rt_alloc call and therefore
// requires fuse_rt.h in scope.
func usesStructAlloc(m *mir.Module) bool {
	for _, fn := range m.Functions {
		for _, blk := range fn.Blocks {
			for _, in := range blk.Insts {
				if in.Op == mir.OpStructNew {
					return true
				}
			}
		}
	}
	return false
}

// usesFloatBitCasts returns true when the module contains an
// OpCast that uses float bit-pattern moves (memcpy through a
// double). string.h must be visible for such casts.
func usesFloatBitCasts(m *mir.Module) bool {
	for _, fn := range m.Functions {
		for _, blk := range fn.Blocks {
			for _, in := range blk.Insts {
				if in.Op == mir.OpCast {
					mode := mir.CastMode(in.Mode)
					if mode == mir.CastFloatToInt || mode == mir.CastIntToFloat {
						return true
					}
				}
			}
		}
	}
	return false
}

// usesRuntimeABI returns true if m contains at least one W16
// runtime-ABI op OR a TermUnreachable block, in which case the
// emitter pulls in fuse_rt.h. TermUnreachable emits a call to
// fuse_rt_abort as the belt-and-braces divergence guard, so the
// header must be visible even for programs that do not otherwise
// touch the runtime.
func usesRuntimeABI(m *mir.Module) bool {
	for _, fn := range m.Functions {
		for _, blk := range fn.Blocks {
			if blk.Term == mir.TermUnreachable {
				return true
			}
			for _, in := range blk.Insts {
				if in.Op >= mir.OpSpawn {
					return true
				}
			}
		}
	}
	return false
}

// cEscapeString renders a Go string as a C string literal, with the
// minimum set of escapes needed for ASCII-plus-newline messages.
// Non-printable bytes are octal-escaped so the output remains
// pure-ASCII safe for any C compiler.
func cEscapeString(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\':
			sb.WriteString("\\\\")
		case '"':
			sb.WriteString("\\\"")
		case '\n':
			sb.WriteString("\\n")
		case '\r':
			sb.WriteString("\\r")
		case '\t':
			sb.WriteString("\\t")
		default:
			if c < 0x20 || c >= 0x7f {
				fmt.Fprintf(&sb, "\\%03o", c)
			} else {
				sb.WriteByte(c)
			}
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

// cName produces a C-safe identifier for a MIR function that is not
// `main`. The scheme folds the module path into the name so that
// multi-module programs at later waves don't collide; at W05 the
// main module is empty so non-main names degenerate to the bare
// function name prefixed with `fuse_`.
func cName(module, name string) string {
	safe := func(s string) string {
		b := make([]byte, 0, len(s))
		for i := 0; i < len(s); i++ {
			c := s[i]
			if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' {
				b = append(b, c)
			} else {
				b = append(b, '_')
			}
		}
		return string(b)
	}
	if module == "" {
		return "fuse_" + safe(name)
	}
	return "fuse_" + safe(module) + "__" + safe(name)
}
